# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=100)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('date', models.DateTimeField(blank=True)),
                ('nature', models.CharField(default='exciting', max_length=20)),
                ('color', models.CharField(default='green', max_length=20)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
