# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('nature', models.CharField(default='exciting', editable=False, max_length=20)),
                ('color', models.CharField(default='red', editable=False, max_length=20)),
            ],
        ),
    ]
