# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pointers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('entry', models.FloatField()),
                ('stopLoss', models.FloatField()),
                ('target', models.FloatField()),
                ('gapUp', models.IntegerField(default=0)),
                ('trend', models.IntegerField(default=0)),
                ('timeSpend', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('totalPoints', models.IntegerField(default=0)),
                ('interval', models.CharField(default='daily', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('date', models.BigIntegerField(default=1)),
                ('nature', models.CharField(default='exciting', editable=False, max_length=20)),
                ('color', models.CharField(default='red', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(default=False)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapi.tickers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
