# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickers',
            old_name='ticker',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='tickers',
            old_name='companyName',
            new_name='Name',
        ),
    ]
