# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='gapUp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointers',
            name='high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointers',
            name='timeSpend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointers',
            name='trend',
            field=models.IntegerField(default=0),
        ),
    ]
