# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_stockdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickers',
            fields=[
                ('ticker', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
