# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_auto_20170612_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
