# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_auto_20170409_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='color',
            field=models.CharField(default='red', editable=False, max_length=20),
        ),
    ]
