# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_pointers_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='type',
            field=models.CharField(default='daily', max_length=10),
        ),
    ]
