# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_tickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickers',
            name='companyName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
