# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0003_auto_20170614_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointers',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pointers',
            name='interval',
        ),
    ]
