# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0004_auto_20170616_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='dividend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointers',
            name='earning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointers',
            name='freshness',
            field=models.IntegerField(default=0),
        ),
    ]
