# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0005_remove_stockdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='date',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
