# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0005_auto_20170619_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterests',
            name='user',
        ),
    ]
