# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0006_stockdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='date',
        ),
    ]
