# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0006_remove_userinterests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickers',
            name='Code',
            field=models.CharField(max_length=100),
        ),
    ]
