# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0007_auto_20170620_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointers',
            name='interval',
            field=models.CharField(default='daily', max_length=20),
        ),
    ]
