# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_auto_20170409_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='color',
            field=models.CharField(default='green', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='nature',
            field=models.CharField(default='exciting', editable=False, max_length=20),
        ),
    ]
